### ISSUE TITLE
Support for generators will be removed

### ISSUE THREAD

**Issue by wzalazar** [koajs/koa-hbs#73]
Hi, I have the following issue, I'm using koa 2.4.1

> koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md

**Comment by shellscape** [comment]
@wzalazar hey there. you didn't actually state what your issue was. might want to start there.

**Comment by wzalazar** [comment]
The problem is Koa2 no support generator anymore. Do you have any plan for supporting Koa2?
This is explained in the link https://github.com/koajs/koa/blob/master/docs/migration.md

**Comment by shellscape** [comment]
I think what you wanted to say was that _Koa v3_ doesn't support the generator patterns any longer. Koa v2 has deprecated support for them. We have no immediate plans for updating this module, but if you're interested in opening a Pull Request to add support, we'd happily examine it for a new major version of koa-hbs.

**Comment by shellscape** [comment]
Closing in favor of #77. Please do take a look at that list and contribute. Invitation is open to all.

**Comment by EmmyMay** [comment]
> 
> 
> I think what you wanted to say was that _Koa v3_ doesn't support the generator patterns any longer. Koa v2 has deprecated support for them. We have no immediate plans for updating this module, but if you're interested in opening a Pull Request to add support, we'd happily examine it for a new major version of koa-hbs.

Why is Koa no longer supporting generator functions?
